### ISSUE TITLE
Too complex tests concern

### ISSUE THREAD

**Issue by mfejzer** [yu55/yagga#18]
@sawickil 
Today I find out comment "TODO: these tests are too complex. Something is wrong...", so created this issue for addressing this concern. 
In my humble opinion adding more complex tests when there are no test coverage for selected area creates kind of safety net, but I could reimplement those tests if current approach is wrong in your opinion.

**Comment by sawickil** [comment]
let's wait for the coming future;)

2015-11-21 19:58 GMT+01:00 Mikołaj Fejzer <notifications@github.com>:
