### ISSUE TITLE
Add validation of Git version

### ISSUE THREAD

**Issue by sawickil** [yu55/yagga#39]
I guess we don't want to support old versions (app may work incorrectly), so add a check on git version. Currently we use 2.5, so let's take this one as a required version.

**Comment by sawickil** [comment]
trying to implement this one

**Comment by sawickil** [comment]
done

**Comment by yu55** [comment]
Where is the PR on this?

**Comment by sawickil** [comment]
it was already merged before xmas - https://github.com/yu55/yagga/pull/46

2015-12-31 20:36 GMT+01:00 Marcin P <notifications@github.com>:
